export const StoriesData = [
    {
        bgPicture:'/src/assets/story/stories1.jpg',
        picture:'/src/assets/frndStory/frnd1.jpg'
    },
    {
        bgPicture:'/src/assets/story/stories2.jpg',
        picture:'/src/assets/frndStory/frnd2.jpg'
    },
    {
        bgPicture:'/src/assets/story/stories3.jpg',
        picture:'/src/assets/frndStory/frnd3.jpg'
    },
    {
        bgPicture:'/src/assets/story/stories4.jpg',
        picture:'/src/assets/frndStory/frnd4.jpg'
    },
    {
        bgPicture:'/src/assets/story/stories5.jpg',
        picture:'/src/assets/frndStory/frnd5.jpg'
    },
]